package relays

// Code generated by scripts/apply-edition.mjs. DO NOT EDIT.

// Host is the compiled-in mainland DERP hostname (Shanghai Lighthouse).
// Desktop can override at runtime with --derp-host / VAV_CN_DERP_HOST.
var Host = "derp.vavapp.art"
