/** Generated by `scripts/apply-brand-pack.mjs`. Default pack: `brand/vav`. */
import type { BrandIdentity, BrandI18nOverlays } from './brandIdentity.ts'

export const BRAND: BrandIdentity = {
  "slug": "vav",
  "displayName": "VAV",
  "displayNameDev": "VAV Dev",
  "appId": "com.vav.app",
  "appIdDev": "dev.vav.app",
  "userDataDir": "vav",
  "userDataDirDev": "vav-dev",
  "copyright": "Copyright © VAV",
  "systemIdentity": "You are {product}, a local coding agent running on the user's {os} machine."
}

export const BRAND_I18N: BrandI18nOverlays = {
  "en": {},
  "zh-CN": {}
}
