/** Generated by `scripts/apply-edition.mjs`. Active: global. */
import type { Edition, EditionId } from './edition.ts'

export const EDITION_ID: EditionId = "global"

export const EDITIONS: Record<EditionId, Edition> = {
  "cn": {
    "id": "cn",
    "site": "https://vavapp.art",
    "derpHost": "derp.vavapp.art",
    "updateFeed": "https://vavapp.art/releases",
    "githubProxy": true,
    "defaultLocale": "zh-CN",
    "legal": {
      "icp": "沪ICP备2026049369号-1"
    }
  },
  "global": {
    "id": "global",
    "site": "https://vavapp.com",
    "derpHost": "",
    "updateFeed": "github",
    "githubProxy": true,
    "defaultLocale": null,
    "legal": {}
  }
} as Record<EditionId, Edition>
