/**
 * Bake edition/*.json into TypeScript, Go, and the static site.
 *
 *   VAV_EDITION=global node scripts/apply-edition.mjs
 *   VAV_EDITION=cn npm run edition:apply
 *
 * The mainland DERP hostname always comes from edition/cn.json so every
 * binary keeps the China relay in the union map. Edition only changes
 * defaults (site, update feed, locale), not capability.
 */
import { existsSync, readdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const dir = join(root, 'edition')
const requested = (process.env.VAV_EDITION || 'global').trim() || 'global'

function readEdition(id) {
  const path = join(dir, `${id}.json`)
  if (!existsSync(path)) throw new Error(`Edition missing: ${path}`)
  const raw = JSON.parse(readFileSync(path, 'utf8'))
  if (!raw || typeof raw !== 'object') throw new Error(`Invalid edition: ${path}`)
  return {
    id: String(raw.id || id),
    site: String(raw.site || '').replace(/\/$/, ''),
    derpHost: typeof raw.derpHost === 'string' ? raw.derpHost.trim() : '',
    updateFeed: typeof raw.updateFeed === 'string' ? raw.updateFeed.trim() : 'github',
    githubProxy: raw.githubProxy !== false,
    defaultLocale: typeof raw.defaultLocale === 'string' ? raw.defaultLocale : null,
    legal: raw.legal && typeof raw.legal === 'object' ? raw.legal : {}
  }
}

const editions = {}
for (const name of readdirSync(dir).filter((n) => n.endsWith('.json')).sort()) {
  const id = name.slice(0, -5)
  editions[id] = readEdition(id)
}
if (!editions[requested]) {
  throw new Error(`Unknown VAV_EDITION=${requested}. Have: ${Object.keys(editions).join(', ')}`)
}

const cn = editions.cn
if (!cn?.derpHost) throw new Error('edition/cn.json must set derpHost')

const generatedTs = `/** Generated by \`scripts/apply-edition.mjs\`. Active: ${requested}. */
import type { Edition, EditionId } from './edition.ts'

export const EDITION_ID: EditionId = ${JSON.stringify(requested)}

export const EDITIONS: Record<EditionId, Edition> = ${JSON.stringify(editions, null, 2)} as Record<EditionId, Edition>
`

writeFileSync(join(root, 'src/shared/edition.generated.ts'), generatedTs)

const generatedGo = `package relays

// Code generated by scripts/apply-edition.mjs. DO NOT EDIT.

// Host is the compiled-in mainland DERP hostname (Shanghai Lighthouse).
// Desktop can override at runtime with --derp-host / VAV_CN_DERP_HOST.
var Host = ${JSON.stringify(cn.derpHost)}
`

writeFileSync(join(root, 'sidecar/tailcatbridge/relays/host_generated.go'), generatedGo)

const siteJs = `/* Generated by scripts/apply-edition.mjs. */
window.VAV_SITE_EDITIONS = ${JSON.stringify(
  {
    global: { site: editions.global.site },
    cn: { site: editions.cn.site, icp: editions.cn.legal?.icp || '' }
  },
  null,
  2
)}
`

writeFileSync(join(root, 'site/edition.js'), siteJs)

console.log(`edition ${requested} (derp ${cn.derpHost})`)
